# Netlify configuration for Justice-Bot

[build]
  command = "npm run build"
  publish = "dist"

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://justice-bot.com/*"
  to = "https://justice-bot.com/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.justice-bot.com/*"
  to = "https://justice-bot.com/:splat"
  status = 301
  force = true

# Redirect old paths to canonical URLs
[[redirects]]
  from = "/terms-of-use"
  to = "/terms"
  status = 301

[[redirects]]
  from = "/account"
  to = "/profile"
  status = 301

[[redirects]]
  from = "/signup"
  to = "/welcome"
  status = 301

[[redirects]]
  from = "/login"
  to = "/welcome"
  status = 301

[[redirects]]
  from = "/generate"
  to = "/forms"
  status = 301

[[redirects]]
  from = "/download"
  to = "/templates"
  status = 301

# 404 for non-existent pages
[[redirects]]
  from = "/payments/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/entitlements"
  to = "/404"
  status = 404

[[redirects]]
  from = "/foo/bar"
  to = "/404"
  status = 404

[[redirects]]
  from = "/path/to/ref"
  to = "/404"
  status = 404

[[redirects]]
  from = "/founders-story"
  to = "/404"
  status = 404

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://vkzquzjtewqhcisvhsvg.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://vkzquzjtewqhcisvhsvg.supabase.co wss://vkzquzjtewqhcisvhsvg.supabase.co;"

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# No cache for HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
