[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "./server"

[[services]]
name = "justice-bot"

[services.env]
PORT = { default = "8080" }
